Problem 1
Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
Output: [ True False False True False]

In [6]:
import numpy as np

In [7]:
array1=np.array([0,10,20,40,60])
array2=np.array([0,40])

print(np.in1d(array1,array2)) # in1d 

[ True False False  True False]


In [11]:
print(np.intersect1d(array1,array2)) # common values of both array

[ 0 40]


In [1]:
a=[1,2,3,4]
x=np.asfarray(a) # Converting the array 'a' to a NumPy array of type float using asfarray()
x

array([1., 2., 3., 4.])

In [2]:
a=np.ones((5,5))

a[1:-1,1:-1]=0 # border with ones and inside are zeros  

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
x=np.empty((3,4))
y=np.full((3,3),6)
print(y)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [9]:
a=np.array([1,2,3],dtype=np.float64)
print(a.size)
print(a.itemsize)
print(a.nbytes) # total bytes of all elements in the array

3
8
24


In [10]:
fvalues = [0, 12, 45.21, 34, 99.91, 32]
f=np.array(fvalues)

np.round(f,1) # round to one decimal place

array([ 0. , 12. , 45.2, 34. , 99.9, 32. ])

Write a NumPy program to get the unique elements of an array
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [12]:
array1=np.array([10,10,20,20,30,30])
print(np.unique(array1))

array2=np.array([[1,1],[2,3]])
print(np.unique(array2))

[10 20 30]
[1 2 3]


In [13]:
array1=np.array([0,10,20,40,60])
array2=np.array([0,40])

print(np.setdiff1d(array1,array2)) #printing unique values in array1 that are not in array2

[10 20 60]


In [24]:
array1=np.array([0,10,20,40,60])
array2=np.array([0,40])

print(np.setxor1d(array1,array2))

[10 20 60]


In [23]:
print(np.all([[True,False],[True,True]]))  # Evaluates to False because at least one element in the array is False

False


In [22]:
a=np.array([[False,False],[False,False]])
print(np.any(a))  # give true if present in a
print(np.any([1,2,3,-89]))

False
True


In [19]:
a=np.array([1,2,3,4])
a=np.tile(a,2)
print(a)

[1 2 3 4 1 2 3 4]


In [18]:
x=np.array([[1,2],[3,4]])
print(np.repeat(x,3))

[1 1 1 2 2 2 3 3 3 4 4 4]


In [17]:
a=np.array([1,2,3,4,5,6])
print(np.argmax(a))
print(np.argmin(a))

5
0


In [16]:
a=np.array([1,2])
b=np.array([4,5])

print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))
print(np.less_equal(a,b))

[False False]
[False False]
[ True  True]
[ True  True]


Write a NumPy program to sort an along the first, last axis of an array.
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]

In [15]:
a=np.array([[4,6,],[2,1]])

x=np.sort(a,axis=0)  #along the rows
print(x)
x=np.sort(x,axis=1)  # along the columns
print(x)

[[2 1]
 [4 6]]
[[1 2]
 [4 6]]


Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
Sample Output:
Original array:
[10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
[4,1,7,3]

In [27]:
nums=np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])

print(np.count_nonzero(nums==10))
print(np.count_nonzero(nums==30))

1
3


Write a NumPy program to remove nan values from a given array.
Sample Output:
Original array:
[200. 300. nan nan nan 700.]
After removing nan values:
[200. 300. 700.]

In [28]:
x=np.array([200, 300, np.nan, np.nan, np.nan, 700])

x=x[np.logical_not(np.isnan(x))]

print(x)

# Use np.isnan(x) to create a boolean array where 'True' represents a NaN value in 'x'. Then, 
# use np.logical_not to invert this boolean array. Finally, use boolean indexing to extract elements 
# from 'x' where the corresponding value in the inverted boolean array is 'True' (i.e., not NaN). 

[200. 300. 700.]


Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
Sample Output:
50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6

In [30]:
a=np.array([10,20,33,44,55,66,77,88,99])

print(np.percentile(a,50))

print(np.percentile(a,80))

55.0
81.4


Write a NumPy program to find indices of elements equal to zero in a NumPy array.
Sample Output:
Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]

In [33]:
nums = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])

result=np.where(nums==0)
print(result)

(array([1, 3, 5], dtype=int64),)


Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
Sample Output:
Original array:
[-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]

In [34]:
x=np.array([-0.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.])
x=np.round(x)
print(x)
x=np.abs(x)
print(x)

[-1. -2. -2.  0.  2.  2.  2.]
[1. 2. 2. 0. 2. 2. 2.]


Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[ 0 0 2 2 2 -7 200]

In [37]:
x = np.array([1, 3, 5, 7, 0])
x=np.diff(x) # this return difference between consecutive elements
print(x)

r2=np.append(x,200)
r2=np.insert(r2,0,[0,0])
print(r2)

[ 2  2  2 -7]
[  0   0   2   2   2  -7 200]


Write a NumPy program to get the indices of the sorted elements of a given array.
Expected Output:
Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]

In [38]:
a=np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

i=np.argsort(a) # sort the indices of a function in ascending order

print(i)

[0 3 4 6 1 5 2]


Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
Sample output:
Original array:
[ 70 50 20 30 -11 60 50 40]
After partitioning on 4 the position:
[-11 30 20 40 50 50 60 70]

In [45]:
arr = np.array([70, 50, 20, 30, -11, 60, 50, 40])

res=np.partition(arr,4)
print(res)

[-11  30  20  40  50  50  60  70]


Compute the euclidean distance between two arrays a and b.
Input:
[1,2,3,4,5]
[4,5,6,7,8]
Euclidean distance is: 6.7082

In [42]:
array1=np.array([1,2,3,4,5])
array2=np.array([4,5,6,7,8])

result=np.sqrt(np.sum(np.square(array2-array1)))
print(result)

6.708203932499369


Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
Input:
array([1, 3, 7, 1, 2, 6, 0, 1])
Desired Output:
array( [2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.

In [46]:
arr=np.array([1,3,7,1,2,6,0,1])
peaks=np.where((arr[1:-1]>arr[:-2]) & (arr[1:-1] >arr[2:]))[0]+1
print(peaks)


# arr[:-2] < arr[1:-1]: This part compares each element in the array arr with its next element. We use array slicing to exclude 
# the last two elements from the comparison since we're comparing each element with its next neighbor. 
# This comparison checks if the current element is smaller than its next element.

# arr[1:-1] > arr[2:]: This part compares each element in the array arr with its previous element. 
# Again, we use array slicing to exclude the first two elements from the comparison since we're 
# comparing each element with its previous neighbor. This comparison checks if the current element is greater than its previous element.

# method2
def find_peaks(arr):
    peaks = []
    for i in range(1, len(arr) - 1):
        if arr[i] > arr[i - 1] and arr[i] > arr[i + 1]:
            peaks.append(i)
    return np.array(peaks)

[2 5]


Find the index of nth repetition of number i .
Inputs
array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5 (from user)
i = 1 (from user)
Output
8

In [47]:
arr=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

def find_nth_repition_index(arr,n,i):
    indece=np.where(arr==1)[0]
    if len(indece)<n:
        return -1
    return indece[n-1]

print(find_nth_repition_index(arr,5,1))

8
